apiVersion: 3
docs:
  docPage: transcription
  featureBase: 'https://github.com/{org}/{repo}/blob/master/docs/transcription{docExt}'
  featurePage: ''
interfaceDefaults: {}
provenanceSpec:
  corpus: 'Dagh Registers Dutch East India Company 1640-1641'
  version: 0.1
typeDisplay: {}
